### ISSUE TITLE
Completion not working with blink.cmp

### ISSUE THREAD

**Issue by saitharun14** [kristijanhusak/vim-dadbod-completion#79] opened 2024-12-19 19:03 UTC
Hello,

First of all thanks for the great plugin. Keep up the good work.

on configuring vim-dadbod-completion with blink.cmp the completions isn't working in the vim-dadbod-ui

**Following is my config of blink.cmp:**

```
return {
	"saghen/blink.cmp",
	version = "v0.*",
	dependencies = {
		"kristijanhusak/vim-dadbod-completion",
	},
	event = "VeryLazy",
	opts = {
		keymap = {
			preset = "default",
			["<CR>"] = { "select_and_accept", "fallback" },
			["<A-1>"] = {
				function(cmp)
					cmp.accept({ index = 1 })
				end,
			},
			["<A-2>"] = {
				function(cmp)
					cmp.accept({ index = 2 })
				end,
			},
			["<A-3>"] = {
				function(cmp)
					cmp.accept({ index = 3 })
				end,
			},
			["<A-4>"] = {
				function(cmp)
					cmp.accept({ index = 4 })
				end,
			},
			["<A-5>"] = {
				function(cmp)
					cmp.accept({ index = 5 })
				end,
			},
			["<A-6>"] = {
				function(cmp)
					cmp.accept({ index = 6 })
				end,
			},
			["<A-7>"] = {
				function(cmp)
					cmp.accept({ index = 7 })
				end,
			},
			["<A-8>"] = {
				function(cmp)
					cmp.accept({ index = 8 })
				end,
			},
			["<A-9>"] = {
				function(cmp)
					cmp.accept({ index = 9 })
				end,
			},
		},
		appearance = {
			use_nvim_cmp_as_default = true,
			nerd_font_variant = "mono",
		},
		sources = {
			default = { "lsp", "path", "snippets", "buffer", "dadbod" },
			providers = {
				dadbod = { name = "Dadbod", module = "vim_dadbod_completion.blink" },
			},
		},
		signature = { enabled = true },
		completion = {
			menu = {
				border = "rounded",
				draw = {
					columns = {
						{ "kind_icon" },
						{ "label", "label_description", gap = 1 },
						{ "source_name" },
					},
				},
			},
			documentation = {
				auto_show = true,
				auto_show_delay_ms = 100,
				window = {
					border = "rounded",
				},
				ghost_text = {
					enabled = false,
				},
			},
		},
	},
	opts_extend = { "sources.default" },
}
```

Any help is appreciated!!! thanks.

**Comment by kristijanhusak** [comment] 2024-12-19 19:38
Does it work with omni?
While in the sql buffer, do `:set omnifunc=vim_dadbod_completion#omni`, and then try to autocomplete something with `<C-x><C-o>`.

**Comment by ruslanSorokin** [comment] 2024-12-21 00:26
Yeah, I have it too after updating to `blink@0.8.0` - dadbod-completion doesn't seem to work anymore.

**Comment by kristijanhusak** [comment] 2024-12-21 08:49
I can't reproduce it. Please provide minimal reproduction.

**Comment by saitharun14** [comment] 2024-12-21 11:11
Hello, after upgrading to blink v0..8 I'm couldn't reproduce the issue. If no is facing this issue I think we can close this. Thanks for the support !!

**Comment by kristijanhusak** [comment] 2024-12-21 16:38
Ok, closing. @ruslanSorokin if it's still not working for you, please open a separate issue with reproducible steps.

**Closed by kristijanhusak** 2024-12-21 16:38 UTC

**Comment by ruslanSorokin** [comment] 2024-12-21 23:26
> Ok, closing. @ruslanSorokin if it's still not working for you, please open a separate issue with reproducible steps.

I'm sorry about the confusion. It was a problem with a third-party plugin that started conflicting with `dadbod-completion` after upgrading to `blink@0.8.0`

**Comment by aemonge** [comment] 2025-02-17 13:58
Same issue and solved with the omnifunc fix:

```lua
        vim.api.nvim_create_autocmd("FileType", {
            pattern = { "sql", "mysql", "plsql" },
            callback = function()
                require("blink.cmp").setup.buffer({
                    sources = { "dadbod" }
                })
                vim.cmd [[
                setlocal omnifunc=vim_dadbod_completion#omni
                ]]
            end
        })
```

Would be nice to be documented

**Comment by kristijanhusak** [comment] 2025-02-18 18:23
Omnifunc is not a requirement for `blink.cmp` completion to work. Your setup seems strange. Check readme how to set up dadbod completion with blink.cmp.
